In [4]:
import numpy as np

# index of array
a = np.arange(16).reshape(4,4)
print(a)
a[0]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([0, 1, 2, 3])

In [5]:
a[:,0]

array([ 0,  4,  8, 12])

In [14]:
a[0:3,0:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [15]:
a[(0,1),(1,1)]

array([1, 5])

In [20]:
# boolean indexing
idx = (a > 0)
print(idx)
a[idx]

b = a[a>0]
print(b)

[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [24]:
a = np.eye(4)
print(a)
b = a[:,0]
print(b)
b[0] = 5
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 0. 0. 0.]
[5. 0. 0. 0.]


In [35]:
#broadcast

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1],[5]])

a + b

array([[ 2,  3,  4],
       [ 9, 10, 11]])

In [41]:
#maximum
x = np.arange(12)
x.shape = (3,4)
print(x)
x.max()
x.max(axis=0)
x.max(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 3,  7, 11])